version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install
      - node/install-packages:
          app-dir: ~/udacity/reactnd-contacts-complete
      - node/install-packages:
          app-dir: ~/udacity/reactnd-contacts-server
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
